### ISSUE TITLE
Pulling Monocular Mode

### ISSUE THREAD

**Issue by Gaozhongpai** [yifliu3/EndoGaussian#4]
Hi, 

Thanks for sharing the codes. I am trying to train monocular mode on `pulling_soft_tissues` data. 

First, I use `DepthAnything `to get the `monodepth `as:

![frame-000000 color_depth](https://github.com/yifliu3/EndoGaussian/assets/4093624/c6198319-9878-4b7f-8ba1-441e4521795a)

Then, I train the model with command:
`python train.py -s dataset/endonerf_sample_datasets/pulling_soft_tissues --port 6017 --expname endonerf/pulling_mono --configs arguments/endonerf/pulling_mono.py`

![image](https://github.com/yifliu3/EndoGaussian/assets/4093624/c55b3f1a-192d-41b1-8198-7b458a9661e9)

The `PSNR `can reach 41.36. However, the point cloud generated is not good as:

![image](https://github.com/yifliu3/EndoGaussian/assets/4093624/4538d4a1-ea6a-4a35-bd76-a26be794a7c7)

Metric evaluation progress: 100%|██████████████████████████████████████| 8/8 [00:00<00:00, 10.29it/s]
Scene:  output/endonerf/pulling_mono/ SSIM :    0.9527130
Scene:  output/endonerf/pulling_mono/ PSNR :   36.5221901
Scene:  output/endonerf/pulling_mono/ LPIPS:    0.0783771
Scene:  output/endonerf/pulling_mono/ RMSE:    7.6948177

Is there anything wrong with my setup? Thanks a lot.

**Comment by yifliu3** [comment]
Hi,

Thanks for your attention. The generated point cloud you display is the initialized points, not the generated point cloud after model training. To produce the generated point cloud, you can use `render.py` and change the `reconstruct` keyword to `True`. Surprisingly, using such initialization can also produce a reasonable point cloud based on our experiments.  

The reason that the initialized point cloud seems not good is caused by the scale-unaware mono-depth estimation. The depth anything model would produce depth maps of different scales for different images, thus directly combining them as we used in the current version would cause point cloud misalignment.

To generate a better initialization, we have modified the code and only used the first image for the Gaussian initialization, achieving a better initialization effect:
<img width="365" alt="tmp" src="https://github.com/yifliu3/EndoGaussian/assets/88416537/40d89afb-b208-4855-bf7e-ec919d63b0f2">

Based on the modified initialization,  the generated point cloud of the test set is shown here:
<img width="411" alt="image" src="https://github.com/yifliu3/EndoGaussian/assets/88416537/039030ff-1b1a-4325-8c3a-ada120020d38">

With updated metric for pulling:
Scene:  output/endonerf/pulling_mono SSIM :    0.9477461
Scene:  output/endonerf/pulling_mono PSNR :   35.8486176
Scene:  output/endonerf/pulling_mono LPIPS:    0.0843981
Scene:  output/endonerf/pulling_mono RMSE:    5.0240870

Thanks a lot for your observation!

**Comment by Gaozhongpai** [comment]
> Hi,
> 
> Thanks for your attention. The generated point cloud you display is the initialized points, not the generated point cloud after model training. To produce the generated point cloud, you can use `render.py` and change the `reconstruct` keyword to `True`. Surprisingly, using such initialization can also produce a reasonable point cloud based on our experiments.
> 
> The reason that the initialized point cloud seems not good is caused by the scale-unaware mono-depth estimation. The depth anything model would produce depth maps of different scales for different images, thus directly combining them as we used in the current version would cause point cloud misalignment.
> 
> To generate a better initialization, we have modified the code and only used the first image for the Gaussian initialization, achieving a better initialization effect: <img alt="tmp" width="365" src="https://private-user-images.githubusercontent.com/88416537/305381104-40d89afb-b208-4855-bf7e-ec919d63b0f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMTgwNTAsIm5iZiI6MTcwODExNzc1MCwicGF0aCI6Ii84ODQxNjUzNy8zMDUzODExMDQtNDBkODlhZmItYjIwOC00ODU1LWJmN2UtZWM5MTlkNjNiMGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDIxMDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMjJlY2I1YmY4M2YxM2I5ZWQ1M2IyNTk3ZDZmYzJkZGZkNDgzN2Q5YTczMjJhMmM2YjVhMDIxZmZmYmY0YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pAlM3VsiiTihihzrlyJPVBb6BKQaPYlixf013RC5Tlc">
> 
> Based on the modified initialization, the generated point cloud of the test set is shown here: <img alt="image" width="411" src="https://private-user-images.githubusercontent.com/88416537/305381673-039030ff-1b1a-4325-8c3a-ada120020d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMTgwNTAsIm5iZiI6MTcwODExNzc1MCwicGF0aCI6Ii84ODQxNjUzNy8zMDUzODE2NzMtMDM5MDMwZmYtMWIxYS00MzI1LThjM2EtYWRhMTIwMDIwZDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDIxMDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMTA2MGZjNDUyMDZmMTMzNGQzZTkxNzBhNmJmNzlhZGYxYjVjZTg4ZTYzZDIxODIwZDg2MDA1ZGVmZmIxOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iUOWo1LBH3cDdjgxhwtTRMfYPR1D5K-vSz3ZRsBBTYQ">
> 
> With updated metric for pulling: Scene: output/endonerf/pulling_mono SSIM : 0.9477461 Scene: output/endonerf/pulling_mono PSNR : 35.8486176 Scene: output/endonerf/pulling_mono LPIPS: 0.0843981 Scene: output/endonerf/pulling_mono RMSE: 5.0240870
> 
> Thanks a lot for your observation!

Scene:  output/endonerf/pulling_mono/ SSIM :    0.9562252
Scene:  output/endonerf/pulling_mono/ PSNR :   37.1470413
Scene:  output/endonerf/pulling_mono/ LPIPS:    0.0617576
Scene:  output/endonerf/pulling_mono/ RMSE:   11.9361257

Thank you for your update. I got higher numbers using your updated code.
